# Generated by Django 4.2.22 on 2026-02-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0035_auto_20230822_2208_squashed_0036_auto_20240311_1028"),
        ("djangocms_page_meta", "0016_auto_20230830_1007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titlemeta",
            name="extended_object",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="cms.pagecontent"
            ),
        ),
    ]
